---
dnsmasq_configuration_file: /etc/dnsmasq.d/10-consul
consul_configuration_file_path: /etc/consul.d/config.json
consul_service_conf_file_path: /etc/systemd/system/consul.service
resolved_conf_file_path: /etc/systemd/resolved.conf